name: update-wishlists
run-name: Check for Updates
# Run once a day at midnight UTC
on: 
  schedule: push
jobs:
  update-repo:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout main, including submodule
      - uses: actions/checkout@v3
        with:
          submodules: true
        # Enter credentials
      - run: git config --global user.email "secrets.EMAIL"
      - run: git config --global user.name "secrets.NAME"
      # Update submodule
      - run: git submodule update --remote
      # Run main python file
      - run: python3 voltron_splitter.py
      # Commit and push changes
      - run: git add .
      - run: git commit -m "update alongside dim-wish-list-sources by 48klocs" || echo "No changes to commit"
      - run: git push origin main
